<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Firebase\\Error' => $vendorDir . '/slimExe/firebase-php/src/firebaseStub.php',
    'Firebase\\FirebaseInterface' => $vendorDir . '/slimExe/firebase-php/src/firebaseInterface.php',
    'Firebase\\FirebaseLib' => $vendorDir . '/slimExe/firebase-php/src/firebaseLib.php',
    'Firebase\\FirebaseStub' => $vendorDir . '/slimExe/firebase-php/src/firebaseStub.php',
);